# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: "0 21 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  SyncYuque:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: yuque_env

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: "Checkout codes"
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.COMMIT_TOKEN }}

      - name: "Setup Node"
        uses: actions/setup-node@v3

      - run: git config --global url."https://${{ secrets.PAT }}@github.com/".insteadOf ssh://git@github.com/

      - name: config git
        run: git config --global user.email "17610906827@163.com"&&git config --global user.name "theo"

      - name: "Sync Yuque"
        env:
          YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
          QINIU_SECRET_ID: ${{ secrets.QINIU_SECRET_ID }}
          QINIU_SECRET_KEY: ${{ secrets.QINIU_SECRET_KEY }}

        run: |
          cd ./src
          npm install 
          npm i -g yuque-hexo
          DEBUG=common-bin YUQUE_TOKEN=$YUQUE_TOKEN SECRET_ID=$QINIU_SECRET_ID SECRET_KEY=$QINIU_SECRET_KEY yuque-hexo sync

          if [ -n "$(git status -s)" ];then
              echo "检查到有变动文件，准备提交"
              npm run build
              cp -r public/* ../docs/
              cd ../
              git add .
              git commit -m "git action schedule sync"
              git push -u origin master
          fi
