# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: yuque_env

    strategy:
      matrix:
        node-version: [15.x]
#     with: # Set the secret as an input
#         YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
    steps:
         - name: 'Checkout codes'
           uses: actions/checkout@v1
            
         - name: 'Sync'
#          env: # Or as an environment variable
#             YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
           uses: actions/setup-node@v3

#        - run: |
#           echo "$YUQUE_TOKEN"    
         - shell: bash

           env:
             YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}

           run: |
             npm install && DEBUG=common-bin YUQUE_TOKEN=$YUQUE_TOKEN yuque-hexo sync
#       with: # Set the secret as an input
#           YUQUE_TOKEN: ${{ secrets.SuperSecret }}
#         env:
#           YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
        
          
#       - uses: actions/checkout@v3
#       - name: Use Node.js ${{ matrix.node-version }} ${{ secrets.YUQUE_TOKEN }}
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}
#         env:
#          YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
  
#       - run: |
#           echo $YUQUE_TOKEN
#       - run: echo "$YUQUE_TOKEN"
